version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
